// Shared team data for consistency across the application
export const teamData = [
  // Board of Directors
  {
    id: 1,
    name: "Mr. Meg Raj Pantha",
    position: "Chairman",
    department: "Board of Directors",
    category: "bods",
    phone: "9857029110",
    email: "chairman@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG", // Using college photo as placeholder for chairman
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 2,
    name: "Mr. Gopal Pandey",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857028806",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 3,
    name: "Mr. Pareshwar Aryal",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857044645",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 4,
    name: "Mr. Ram Prasad Gaire",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857025762",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 5,
    name: "Mr. Basanta Bdr. KC",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857050680",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 6,
    name: "Mr. Resham Giri",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857030874",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 7,
    name: "Mr. Subhash Kafle",
    position: "Board Member",
    department: "Board of Directors",
    category: "bods",
    phone: "9857039315",
    email: "board@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 8,
    name: "Mr. Lal Bahadur Gurung",
    position: "Internal Audit Committee",
    department: "Board of Directors",
    category: "bods",
    phone: "9857039801",
    email: "audit@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 9,
    name: "Mr. Yuvraj Panta",
    position: "Internal Audit Committee",
    department: "Board of Directors",
    category: "bods",
    phone: "9847052086",
    email: "audit@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 10,
    name: "Mrs. Saraswati Puri",
    position: "Internal Audit Committee",
    department: "Board of Directors",
    category: "bods",
    phone: "9847384474",
    email: "audit@westernmegacollege.edu.np",
    image: "/staffs/college_photo.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },

  // Principal
  {
    id: 11,
    name: "Adv. Kishu Sharma",
    position: "Principal",
    department: "Administration",
    category: "principal",
    phone: "9857070832",
    email: "kishusharma@westernmegacollege.edu.np",
    image: "/staffs/Adv. Kishu Sharma Principal.JPG",
    specialization: "Educational Administration & Legal Affairs",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "https://www.linkedin.com/in/kishu-sharma-6a7675160/",
      instagram: "#",
    },
  },

  // Academic Staff
  {
    id: 12,
    name: "Mr. Prem Pokhrel",
    position: "Exam Coordinator",
    department: "Academic Department",
    category: "faculty",
    phone: "BHM | MBA",
    email: "prempokhrel@westernmegacollege.edu.np",
    image: "/staffs/Prem_Pokhrel_Exam-Coordinator.jpg",
    specialization: "BHM | MBA Programs",
    courses: ["BHM", "MBA"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "https://www.linkedin.com/in/prem-pokhrel/",
      instagram: "#",
    },
  },
  {
    id: 13,
    name: "Mrs. Kalpana Neupane",
    position: "Student Welfare (SWD)",
    department: "Student Affairs",
    category: "faculty",
    phone: "BHM | MBA",
    email: "kalpananeupane@westernmegacollege.edu.np",
    image: "/staffs/KALPANA_NEUPANE_SWD.JPG",
    specialization: "Student Welfare & Development",
    courses: ["BHM", "MBA"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "https://www.linkedin.com/in/kalpana-neupane-1b431a161/",
      instagram: "#",
    },
  },
  {
    id: 14,
    name: "Dr. Bhagwati Prasad Chaudhary",
    position: "Faculty Member",
    department: "Business Faculty",
    category: "faculty",
    email: "bhagwati@westernmegacollege.edu.np",
    image: "/staffs/Dr.Bhagwati Prasad Chaudhary Photograph..png",
    specialization: "Business and Management Studies",
    courses: ["MBA", "BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 15,
    name: "Mr. Lalitman Shrestha",
    position: "Faculty Member",
    department: "Finance Faculty",
    category: "faculty",
    email: "lalitman@westernmegacollege.edu.np",
    image: "/staffs/Mr.Lalitman Shrestha Photograph..jpg",
    specialization: "Banking and Accountancy",
    courses: ["MBA", "BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 16,
    name: "Chef Bikash Khatri Thapa",
    position: "Practical Instructor",
    department: "Hospitality Faculty",
    category: "faculty",
    email: "bikash@westernmegacollege.edu.np",
    image: "/staffs/chef_bikash khatri thapa.jpg",
    specialization: "Culinary Arts & Food Production",
    courses: ["BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 17,
    name: "Mr. Kabi Raj Giri",
    position: "Practical Instructor",
    department: "Hospitality Faculty",
    category: "faculty",
    email: "kabiraj@westernmegacollege.edu.np",
    image: "/staffs/kabiraj giri.jpeg",
    specialization: "Hospitality Operations",
    courses: ["BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 18,
    name: "C.A. Prem Subedi",
    position: "Faculty Member",
    department: "Finance Faculty",
    category: "faculty",
    email: "premsubedi@westernmegacollege.edu.np",
    image: "/staffs/C.A.Prem Subedi Photographs.jpeg",
    specialization: "Accounting & Finance",
    courses: ["MBA", "BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 19,
    name: "Adv. Arjun Kafle",
    position: "Faculty Member",
    department: "Legal Faculty",
    category: "faculty",
    email: "arjunkafle@westernmegacollege.edu.np",
    image: "/staffs/Adv.Arjun Kafle Photograph..png",
    specialization: "Legal Studies & Business Law",
    courses: ["MBA", "BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 20,
    name: "Er. Ram Prasad Jaishi",
    position: "Faculty Member",
    department: "Engineering Faculty",
    category: "faculty",
    email: "ramprasad@westernmegacollege.edu.np",
    image: "/staffs/Er.Ram Prasad Jaishi Photograph..png",
    specialization: "Engineering & Technology",
    courses: ["BHM"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 21,
    name: "Mr. Narayan Prasad Bhusal",
    position: "Faculty Member",
    department: "Academic Faculty",
    category: "faculty",
    email: "narayan@westernmegacollege.edu.np",
    image: "/staffs/Mr.Narayan Prasad Bhusal Photographh..png",
    specialization: "General Studies",
    courses: ["BHM", "MBA"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 22,
    name: "Mr. Romnath Sharma",
    position: "Faculty Member",
    department: "Academic Faculty",
    category: "faculty",
    email: "romnath@westernmegacollege.edu.np",
    image: "/staffs/Mr.Romnath Sharma Photograph.jpg",
    specialization: "Academic Studies",
    courses: ["BHM", "MBA"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 23,
    name: "Mrs. Suparna Chattergee",
    position: "Faculty Member",
    department: "Academic Faculty",
    category: "faculty",
    email: "suparna@westernmegacollege.edu.np",
    image: "/staffs/Mrs.Suparna Chattergee Photograph..jpg",
    specialization: "Academic Studies",
    courses: ["BHM", "MBA"],
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },

  // Administrative Staff
  {
    id: 24,
    name: "Ms. Prasansha",
    position: "Chief Accountant",
    department: "Finance",
    category: "staff",
    email: "accounts@westernmegacollege.edu.np",
    image: "/staffs/PRASANSHA_CHIEF_ACCOUNTANT.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 25,
    name: "Ms. Usha",
    position: "Account Assistant",
    department: "Finance",
    category: "staff",
    email: "accounts@westernmegacollege.edu.np",
    image: "/staffs/USHA_ACCOUNT_ASSISTANT.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 26,
    name: "Ms. Aliza Bajracharya",
    position: "Librarian",
    department: "Library",
    category: "staff",
    email: "library@westernmegacollege.edu.np",
    image: "/staffs/ALIZA_BAJRACHARYA_LIBRARIAN.JPG",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 27,
    name: "Ms. Bishakha Aryal",
    position: "Receptionist",
    department: "Administration",
    category: "staff",
    email: "reception@westernmegacollege.edu.np",
    image: "/staffs/Bishaka Aryal.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 28,
    name: "Mr. Bishnu Neupane",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Bishnu Neupane.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 29,
    name: "Mr. Chudamani Basyal",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/chudamani basyal.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 30,
    name: "Mr. Krishna Bhattarai",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Krishna Bhattarai.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 31,
    name: "Mr. Rajiv Khanal",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Rajiv Khanal.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 32,
    name: "Mr. Sangyat Shrestha",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Sangyat Shresthaa.jpg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 33,
    name: "Mr. Shan Thapa",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Shan_Thapa.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 34,
    name: "Mr. Sudarshan Kandel",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/sudarshan kandel.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 35,
    name: "Mr. Suraj Shakya",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Suraj Shakya.jpeg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
  {
    id: 36,
    name: "Mr. Sushil Gyawali",
    position: "Administrative Staff",
    department: "Administration",
    category: "staff",
    email: "admin@westernmegacollege.edu.np",
    image: "/staffs/Sushil Gyawali.jpg",
    socialLinks: {
      facebook: "#",
      twitter: "#",
      linkedin: "#",
      instagram: "#",
    },
  },
];

export const getTeamById = (id: number) => {
  return teamData.find((member) => member.id === id);
};

export const getTeamByCategory = (category: string) => {
  return teamData.filter((member) => member.category === category);
};

export const getBoardOfDirectors = () => {
  return teamData.filter((member) => member.category === "bods");
};

export const getPrincipal = () => {
  return teamData.filter((member) => member.category === "principal");
};

export const getFaculty = () => {
  return teamData.filter((member) => member.category === "faculty");
};

export const getStaff = () => {
  return teamData.filter((member) => member.category === "staff");
};
